fix: SignupページのCSSをつくる
yukikamome316/alcoho-rhythm pull request #12
Opened 2024-10-21 10:24 UTC by hana-rs

2024-10-21 10:47 UTC, hana-rs commented
とりあえずのデザインです

2024-10-21 15:02 UTC, yukikamome316 requested changes
https://github.com/yukikamome316/alcoho-rhythm/actions/runs/11438613683/job/31820565000

prettier のチェックで Actions が落ちているから、以下のコマンドを打ってコードを修正してほしい！
```
cd client
pnpm run lintfix
```

2024-10-21 15:02 UTC, yukikamome316 commented
@hana-rs 
PRに実装した画面のスクリーンショット(動作確認証跡)を載せてほしい！

2024-10-27 06:19 UTC, yukikamome316 reviewed
以下の部分、余裕があれば中央揃えしておいてほしい
![image](https://github.com/user-attachments/assets/ae4da2b8-6e24-4621-95ff-1f869b5a0718)

2024-10-27 06:21 UTC, yukikamome316 requested changes
追加でこれもお願いします！

2024-10-27 06:21 UTC, yukikamome316 commented on client/src/Signup.css
`client/src/signup/Signup.css` に移動できるかな？

2024-10-27 06:21 UTC, yukikamome316 commented on client/src/Signup.jsx
これも `client/src/signup/Signup.jsx` に移動してほしい！

2024-10-28 10:35 UTC, yukikamome316 requested changes

2024-10-28 10:35 UTC, yukikamome316 commented on client/src/Signup.jsx
体重を入力させる画面を作ってほしい

2024-10-30 01:00 UTC, yukikamome316 requested changes

2024-10-30 01:00 UTC, yukikamome316 commented on client/src/Signup.jsx
> +import "./Signup.css"; // CSSファイルインポート
```suggestion
import "./Signup.css";
```

2024-10-30 01:00 UTC, yukikamome316 commented on client/src/Signup.jsx
>      console.log("Form submitted:", formData);
`/api/signup:8000` が実装されている前提で POST を投げてしまっていいと思う
https://www.newt.so/docs/form-app-fetch-api-installation

2024-11-01 00:07 UTC, hana-rs commented
POST全然自信ないです。見当はずれなことやってたらすみません。
中央ぞろえはちょっと時間なかったので保留にしました。

2024-11-01 00:17 UTC, yukikamome316 requested changes

2024-11-01 00:17 UTC, yukikamome316 commented on client/src/signup/Signup.jsx
> +      });
`console.log` してる理由ってある？

2024-11-01 00:17 UTC, yukikamome316 commented on client/src/signup/Signup.jsx
>      console.log("Form submitted:", formData);
`handleSubmit` が `async` ではなくて、 `await fetch` になっていないから API からのレスポンスが返ってくる前に `console.log` の実行が先行してしまう可能性があるね

2024-11-01 00:17 UTC, yukikamome316 commented on client/src/signup/Signup.jsx
> +    fetch("http://localhost:8000/signup", {
`fetch` した後にレスポンスを見て、ステータスコードが 200 になっていない場合のエラーハンドリングが必要だね

2024-11-01 00:20 UTC, yukikamome316 commented on client/src/signup/Signup.jsx
>      console.log("Form submitted:", formData);
`fetch` は `Promise` だから、 `.then` で処理する方が楽そう

2024-11-01 14:14 UTC, yukikamome316 requested changes
もう一点お願い！

2024-11-01 14:14 UTC, yukikamome316 commented on client/src/signup/Signup.jsx
> +    fetch("http://localhost:8000/signup", {
入力によっては
```plain
{
  error: "This email already exist."
}
```
みたいなレスポンスが返ってくる場合もあって、その場合もエラーメッセージをフロントエンドで描画しないとまずそう
詳細は `/api/signup` のバックエンド実装を見て、それぞれのエラーに対応するエラーハンドリングをしてほしい！

2024-11-02 05:43 UTC, hana-rs commented
自己流でやってしまったところもあったので、ChangeRequestの修正は置いておいて
とりあえず全部愚直に記事の通りに書き直しました。(JSON形式の方です)

2024-11-02 07:30 UTC, yukikamome316 commented
@hana-rs 
> 自己流でやってしまったところもあったので、ChangeRequestの修正は置いておいて とりあえず全部愚直に記事の通りに書き直しました。(JSON形式の方です)

OK、確認します

2024-11-02 07:34 UTC, yukikamome316 requested changes

2024-11-02 07:34 UTC, yukikamome316 commented on client/src/App.jsx
`main` ブランチとのコンフリクトを解消してほしい

2024-11-02 07:34 UTC, yukikamome316 commented on client/src/signup/Signup.jsx
> +      password: document.querySelector('input[name="password"]').value,
L5 で `formData` を状態として持っているから、以下のコードで実装するべきだと思う
```suggestion
      username: formData.username,
      weight: formData.weight,
      email: formData.email,
      password: formData.password,
```

2024-11-02 07:34 UTC, yukikamome316 commented on client/src/signup/Signup.jsx
> +      .then((response)=>response.json())
https://github.com/yukikamome316/alcoho-rhythm/pull/12/files#r1825866418
これをこの `then` の中でやればよさそう

2024-11-03 05:10 UTC, hana-rs commented
リダイレクトできてないかもですまだ

2024-11-03 13:11 UTC, yukikamome316 requested changes
ある程度完成形に近い感じに改善したので、この部分だけお願いします！

2024-11-03 13:11 UTC, yukikamome316 commented on client/src/signup/Signup.jsx
> +      throw new Error(resJson.error);
この部分を実装してほしい！

2024-11-04 19:50 UTC, hana-rs commented
なんかfail to fetchになっちゃって止まってしまいました
signup.jsxの中身、Refactor: フォーマットのときのをコピペしてもFailなっちゃいます。

2024-11-05 10:06 UTC, yukikamome316 requested changes

2024-11-05 10:06 UTC, yukikamome316 commented on client/src/signup/Signup.jsx
> +      {error && <div className="error-message">{error}</div>} {}
`error` が定義されてないからビルドが通ってない
<img width="320" alt="image" src="https://github.com/user-attachments/assets/ccb60f33-4f2c-48cc-8444-63107a807d69">

2024-11-05 10:09 UTC, yukikamome316 commented
> なんかなにやってもfail to fetchになります。 signup.jsxの中身、Refactor: フォーマットのときのをコピペしてもFailなっちゃいます。

`git reset` して戻したらちゃんと動くよ

<img width="601" alt="image" src="https://github.com/user-attachments/assets/10a35031-63c6-47a5-ad8b-4911c67671c8">

<img width="821" alt="image" src="https://github.com/user-attachments/assets/f2c73fb6-b936-4e24-a048-1a97d37303db">

2024-11-06 18:09 UTC, hana-rs commented on client/src/signup/Signup.jsx
> +      {error && <div className="error-message">{error}</div>} {}
const [error, setError] = useState("");
定義って15行目のこれ↑ではなく別のなにかですか？

2024-11-06 19:04 UTC, hana-rs commented
Refactor: フォーマットの時点では問題ないんですが、辻さんがコミットした時点＋(error定義済)でfail to fetchなるので、辻さんの変更時点で問題があるように思います。
どうしましょうか？コミット戻して自分でリダイレクトやったほうがいいですか？

2024-11-07 06:08 UTC, yukikamome316 approved these changes

2024-11-07 06:08 UTC, merged