feat: SignupAPIを実装
yukikamome316/alcoho-rhythm pull request #14
Opened 2024-10-21 13:32 UTC by nomanoma121

サインアップのAPIを実装しました。
機能としては`users`テーブルに`username`, `weight`, `email`, `password`の追加ができます。
![スクリーンショット 2024-10-21 222506](https://github.com/user-attachments/assets/b32541ec-702f-4cb3-bf61-43368660b0f2)

プラスで動作確認しやすいように`queries.js`のそれぞれのテーブルのクエリに`findAll`を追加しました。不要であれば消します。

動作確認用
```
curl -X POST http://localhost:8000/api/signup   -H "Content-Type: application/json"   -d '{
    "username": "ほげほげ",
    "weight": 60.3,
    "email": "hogehoge@mail",
    "password": "hogehoge"
  }
```
```
curl http://localhost:8000
```

2024-10-21 13:43 UTC, yukikamome316 requested changes

2024-10-21 13:43 UTC, yukikamome316 commented on server/server.js
> +    param.password
パスワードの生データをそのままDBに保存するのはセキュリティ上かなりまずくて、代わりにパスワードをハッシュ化したものを持っておくのが慣例だよ！
bcryptというライブラリが有名だから、これを使ってハッシュ化・照合してみようか

```bash
pnpm install bcrypt
```

https://qiita.com/arihori13/items/61aaf2c223dfd99a87f0

2024-10-21 13:43 UTC, yukikamome316 commented on server/server.js
> +  return c.json({ message: "Successfully created!" });
```suggestion
  return c.json({ message: "Successfully created." });
```

ここはシンプルにこれでいいと思うw

2024-10-21 13:43 UTC, yukikamome316 commented on server/server.js
> +});
これって何かな？

2024-10-21 13:43 UTC, yukikamome316 commented on server/queries.js
`findAll` は必要になったら追加しよう
現時点では消して欲しい！

2024-10-21 15:39 UTC, nomanoma121 commented on server/server.js
> +    param.password
おそらくハッシュ化はできました。照合は`bcrypt.compare`を使って行った方がいいでしょうか？

2024-10-22 00:29 UTC, yukikamome316 requested changes

2024-10-22 00:29 UTC, yukikamome316 commented on server/server.js
> +  );
例外処理を追加しよう！
既に取られてる username や登録されてる email が `param` に渡された場合に、テーブルの `UNIQUE` 制約によって `db.prepare().run()` は正常終了せずに例外を投げるはずだから、 `/api/signup` への POST リクエストは 500 Internal Server Error を返してしまうはず

2024-10-22 00:29 UTC, yukikamome316 commented on server/server.js
> +    param.email,
`param`の各変数に適切な値が入る前提で `INSERT` してるけど、そうじゃない場合も考えられるから入力バリデーションをしよう！
このままだと0文字や1文字のパスワードであったり、ユーザー名に変な記号を使えたり、「a」とかの適当な文字列をメールアドレスとして登録できてしまう...

2024-10-22 00:29 UTC, yukikamome316 commented on server/server.js
> +    const hash = await bcrypt.hash(password, 12);
マジックナンバーを避けるために、「12」を直接関数として渡すよりもファイル上部の `import` より下側に
`const SALT_ROUNDS = 12;`
みたいな定数を追加して、ここで渡すのがいいと思う！

2024-10-22 04:15 UTC, nomanoma121 commented on server/server.js
> +    const hash = await bcrypt.hash(password, 12);
わかりました。気を付けます！

2024-10-22 04:54 UTC, nomanoma121 commented on server/server.js
> +  );
`UNIQUE`制約をテーブルにつけていないのですがここで修正してもいいですか？

2024-10-27 02:25 UTC, yukikamome316 requested changes

2024-10-27 02:25 UTC, yukikamome316 commented on server/server.js
> +const SALT_ROUNDS = 12;
```suggestion

const SALT_ROUNDS = 12;
```

スタイル的に `import` から一行開けた方がみやすそう！

2024-10-27 02:25 UTC, yukikamome316 commented on server/server.js
> +  const isPasswordValid = password && password.length >= 8;
`8` もマジックナンバーだから定数として切り離そう

2024-10-27 02:25 UTC, yukikamome316 commented on server/server.js
> +const validateInput = (username, weight, email, password) => {
全ての入力を1つの関数で検証するより、 `username`, `weight`, `email`, `password` それぞれのバリデーション用の関数を定義したほうがいいよ！
発展的な内容になるけど、そうした方がテストを書きやすい！

2024-10-27 02:25 UTC, yukikamome316 commented on server/server.js
> +        message: "Database error: " + error.message,
内部で起きてるエラーの原因を、クライアント側に詳細に教えない方がいいと思う
特にDB関連だとなおさら

2024-10-28 09:41 UTC, yukikamome316 requested changes

2024-10-28 09:41 UTC, yukikamome316 commented on server/server.js
> +
各エンドポイントで `HTTPException` が `throw` されたとき、それを適切にハンドリングする必要があるから以下のようなエラーハンドリングの処理を追加した方がいいよ！

```js
app.onError((err, c) => {
  if (err instanceof HTTPException) {
    return err.getResponse()
  }
  return new HTTPException(500, {"message": "Internal server error"});
});
```

2024-10-28 09:41 UTC, yukikamome316 commented on server/server.js
> +
ここの空白を消そう
```suggestion

```

2024-10-28 09:41 UTC, yukikamome316 commented on server/server.js
> +        message: "Database error"
ここも空白を消そう
```suggestion
        message: "Database error"
```

2024-10-28 09:41 UTC, yukikamome316 commented on server/server.js
> +  if (!isWeightValid) throw new HTTPException(400, {"message": "Weight must be grater than 0."});
無駄な空白を消して、{}を使おう
```suggestion
  if (!isWeightValid) {
    throw new HTTPException(400, {"message": "Weight must be grater than 0."});
  }
```

2024-10-28 09:41 UTC, yukikamome316 commented on server/server.js
> +  if (!isPasswordValid) throw new HTTPException(400, {"message": "Password must be at least 8 characters long."});
無駄な空白を消して、{}を使おう！
```suggestion
  if (!isPasswordValid) {
    throw new HTTPException(400, {"message": "Password must be at least 8 characters long."});
  }
```

2024-10-28 09:41 UTC, yukikamome316 commented on server/server.js
> +  }
この部分は、ファイル下部で返したレビューにある `onError` を実装すれば、 try-catch 文を書かずに以下の1行で書くことができるよ

```suggestion
  validateUsername(param.username);
  validateWeight(param.weight);
  validateEmail(param.email);
  validatePassword(param.password);
```

2024-10-28 09:41 UTC, yukikamome316 commented on server/server.js
> +  if (!isUsernameValid) throw new HTTPException(400, {"message": "Invalid username format."});
```suggestion
  if (!isUsernameValid) {
    throw new HTTPException(400, {"message": "Invalid username format."});
  }
```

2024-10-28 09:41 UTC, yukikamome316 commented on server/server.js
> +  if (!isEmailValid) throw new HTTPException(400, {"message": "Invalid email format."});
```suggestion
  if (!isEmailValid) {
    throw new HTTPException(400, {"message": "Invalid email format."});
  }
```

2024-10-28 11:05 UTC, yukikamome316 approved these changes
LGTM！お疲れ様～！

2024-10-28 11:05 UTC, merged