feat: registerAPI
yukikamome316/alcoho-rhythm pull request #24
Opened 2024-11-04 08:17 UTC by shigekk

2024-11-04 13:54 UTC, yukikamome316 reviewed
全体的によく実装出来てると思う

2024-11-04 13:54 UTC, yukikamome316 commented on server/server.js
> +  const token = c.req.cookie(COOKIE_NAME);
Hono Cookie Helper の `getCookie` を使おう
https://hono.dev/docs/helpers/cookie

2024-11-06 12:25 UTC, yukikamome316 commented
@shigekk 
GET `/api/register` の実装もお願い！

2024-11-10 12:08 UTC, yukikamome316 commented
@shigekk 
APIを叩いた画面のスクショとか証跡をPRの一番上に載せてほしい

2024-11-10 12:29 UTC, yukikamome316 requested changes

2024-11-10 12:29 UTC, yukikamome316 commented on server/server.js
> +});
```suggestion
});

```

2024-11-10 12:29 UTC, yukikamome316 commented on server/server.js
> +    return c.json(records);
```suggestion
    return c.json(records);
```

2024-11-10 12:29 UTC, yukikamome316 commented on server/server.js
> +import { deleteCookie, setCookie, getCookie } from "hono/cookie";
```suggestion
import { deleteCookie, setCookie, getCookie } from "hono/cookie";
```

2024-11-10 12:29 UTC, yukikamome316 commented on server/server.js
> +    const records = db.prepare(queries.DrinkingRecords.findByUserId).all(userId);
`queries.DrinkingRecords.findByUserId` 定義し忘れてるよ！！

2024-11-10 12:29 UTC, yukikamome316 commented on server/server.js
> +    throw new HTTPException(500, { message: "Database error" });
データベースでエラーが起こっていることは、セキュリティ対策上第三者に教えない方がいい
errorをそのまま `throw` すればいいと思う

2024-11-10 12:32 UTC, yukikamome316 commented
@shigekk 
それと、よく考えたら `register` に `GET` って英語的におかしいので、申し訳ないけど `/api/records` にしてもらえないかな？
あと余裕があれば `PUT` と `DELETE` の追加にもチャレンジしてみてほしい！

2024-11-12 15:49 UTC, yukikamome316 submitted a review, later dismissed

2024-11-13 10:58 UTC, nomanoma121 commented
あとPOSTでは`condition`が1 ~ 5の間にあることを確認しているのに対し、PUTでは行っていないため`amount`が0以上である確認も含めやってもいいんじゃないかと思います！

2024-11-13 11:18 UTC, nomanoma121 commented
動作確認は完了して、バリデーションもすべて動作していました。

2024-11-13 15:35 UTC, yukikamome316 commented
@nomanoma121 
> 動作確認は完了して、バリデーションもすべて動作していました。

確認ありがとう！前のコメントのやつ修正したらまたReviewお願いしたい！

2024-11-17 06:07 UTC, yukikamome316 commented
@nomanoma121 
レビューお願いします！
問題なければ Approve ください

2024-11-17 15:45 UTC, nomanoma121 submitted a review, later dismissed

2024-11-17 15:45 UTC, nomanoma121 commented on server/server.js
> +
```suggestion
//飲酒量のバリデーション
if (param.amount < 0) {
  throw new HTTPException(400, { message: "amount must  be greater than or equal to 0." });
}
```
動作確認しているときに思ったんですが、クライアント側で`amount`が0以上かどうかバリデーションしているのでもしかしたらサーバー側でもやっていいのかなと思います！

2024-11-20 13:57 UTC, nomanoma121 approved these changes, later dismissed
特に問題ないと思います！

2024-11-20 16:55 UTC, nomanoma121 approved these changes, later dismissed

2024-11-20 16:59 UTC, nomanoma121 approved these changes

2024-11-20 17:00 UTC, nomanoma121 submitted a review, later dismissed

2024-11-21 11:00 UTC, nomanoma121 approved these changes

2024-11-21 11:11 UTC, merged