fix: 登録画面でAPIを呼ぶ
yukikamome316/alcoho-rhythm pull request #27
Opened 2024-11-24 04:09 UTC by shigekk

2024-11-24 05:36 UTC, yukikamome316 requested changes

2024-11-24 05:36 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +      fetch("/api/records", {
```suggestion
      fetch("http://localhost:8000/api/records", {
```

2024-11-24 05:36 UTC, yukikamome316 commented on client/src/register/Register.jsx
サインインしていないユーザーが /register にアクセスした場合は、 /signin にリダイレクトさせるかサインインを促す画面を出すのがいいと思う
実装は react-router-dom の機能で出来そう
https://medium.com/@ivailohr/using-react-router-to-hide-content-from-unauthorized-users-1af32918f64b

2024-11-24 05:36 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +            throw new Error("データの送信に失敗しました");
エラーが発生したことを開発者ツールを使わなくてもユーザーが認識できるようにしてほしい

2024-11-24 05:36 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +          console.error(error);
https://github.com/yukikamome316/alcoho-rhythm/pull/27#discussion_r1855355132 と同様

2024-11-24 05:36 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +  };
```suggestion
  const computeTotalAlcohol = () => {
    const alcoholData = [
      { quantity: alcoholQuantities.beer350, volume: 350, percentage: 0.05 },
      { quantity: alcoholQuantities.beer500, volume: 500, percentage: 0.05 },
      { quantity: alcoholQuantities.highball350, volume: 350, percentage: 0.07 },
      { quantity: alcoholQuantities.highball500, volume: 500, percentage: 0.07 },
      { quantity: alcoholQuantities.wine, volume: 120, percentage: 0.12 },
      { quantity: alcoholQuantities.sake, volume: 180, percentage: 0.15 },
      { quantity: alcoholQuantities.shochu, volume: 100, percentage: 0.25 },
      { quantity: alcoholQuantities.whiskey, volume: 30, percentage: 0.4 },
    ];

    const total = alcoholData.reduce((acc, { quantity, volume, percentage }) => {
      return acc + quantity * volume * percentage;
    }, 0);

    return total;
  };
```

アルコール度数をそのままコードに埋め込んでしまうと、他の人がこのコードを見た時に数字の意味を理解するのに時間がかかってしまう(「紛らわしい数」「magic number」などと呼ばれる)から、定数として切り離すと読みやすくなると思う

それと `let` は最終手段で、 `const` を使えるときは使うことを心掛けるといいと思う！

2024-11-24 05:36 UTC, yukikamome316 commented on client/src/register/Register.jsx
>    const [dateError, setDateError] = useState(false);
`isDateValid` の方がしっくりくる
trueとfalseを反転させる必要があるけど

2024-11-24 11:04 UTC, shigekk commented
11時半くらいに家帰るので、その後すぐ直します

2024-11-25 14:59 UTC, yukikamome316 requested changes
とりあえずこれだけ対応お願い！

2024-11-25 14:59 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +        {!isDateValid && (
何も入力してない状態でもエラーメッセージが表示されてしまうから、何か入力して初めてバリデーションチェックが走るようにしてほしい

![image](https://github.com/user-attachments/assets/ebc1a72e-4c20-4d36-a1ec-e2b557c912ee)

2024-11-25 14:59 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +    fetch("http://localhost:8000/api/records/check", {
api/records/check なんて存在しないよ...？

2024-11-25 14:59 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +    fetch("http://localhost:8000/api/records/check", {
JWTの中身を見るか、エンドポイントを実装するかどちらか一方で対応してほしい

2024-11-25 14:59 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +  }, [navigate]);
これ自分の環境だと動作しないんだけど、そっちで動作確認取れてる？

2024-11-27 04:58 UTC, yukikamome316 requested changes

2024-11-27 04:58 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +
これもういらなくない？

2024-11-27 04:58 UTC, yukikamome316 commented on client/src/App.jsx
>            <Route path="/register" element={<Register />} />
registerに関しても同じように`Navigate`させてほしい

2024-11-27 04:59 UTC, yukikamome316 commented on client/src/App.jsx
>            <Route path="/register" element={<Register />} />
実装はいい感じ！

2024-11-27 13:40 UTC, yukikamome316 commented on client/src/App.jsx
> +
https://github.com/user-attachments/assets/433a2349-a741-4890-a297-38362415287c

2024-11-27 13:42 UTC, yukikamome316 requested changes
これだけお願いしたい！

2024-11-27 13:42 UTC, yukikamome316 commented on client/src/App.jsx
> +
ここの処理が上手くいってなさそう

https://github.com/user-attachments/assets/433a2349-a741-4890-a297-38362415287c

2024-11-27 17:28 UTC, shigekk commented on client/src/App.jsx
> +
これってサーバ側も修正する必要がある感じですか

2024-11-27 23:48 UTC, yukikamome316 commented on client/src/App.jsx
> +
いらなさそう

https://ja.next-community-docs.dev/docs/app/api-reference/functions/cookies

https://zenn.dev/kterada/articles/376aefc9bcfb28

https://qiita.com/Yasushi-Mo/items/5d1a6f7929c96ec7d110

2024-11-28 11:15 UTC, shigekk commented on client/src/App.jsx
> +
これでtokenって名前のクッキーがあるかを判定できると思ってるのですが、何でできないのかわからないです💦
```
function isAuthenticated() {
  const cookies = document.cookie.split(";").map((cookie) => cookie.trim());
  return cookies.some((cookie) => cookie.startsWith("token="));
}
```

2024-11-29 13:35 UTC, shigekk commented on client/src/App.jsx
> +
リロードするまで認証が確認されないのが原因だったのかもしれないです

2024-11-30 13:19 UTC, yukikamome316 commented on client/src/App.jsx
> +    const interval = setInterval(checkAuth, 1000); // 1秒ごとにチェック
毎秒も確認しなくていいんじゃないか？それこそ3秒に1回とか

2024-12-01 04:21 UTC, yukikamome316 requested changes
中央揃えのスタイルが適応されてないけど、動作確認取ってる？
![image](https://github.com/user-attachments/assets/c80a7528-cb1d-42e1-9a36-0217232f4446)

2024-12-01 06:49 UTC, shigekk commented
間違ってcssのimport消してましたm(__)m
tokenがあればregisterを表示する動作は問題ないと思います

2024-12-02 02:26 UTC, yukikamome316 approved these changes
LGTM、お疲れ様！

2024-12-02 03:14 UTC, merged