feat: ダッシュボードの実装
yukikamome316/alcoho-rhythm pull request #31
Opened 2024-11-30 22:47 UTC by nomanoma121

ダッシュボードの大枠のロジックを実装しました。

2024-12-01 05:17 UTC, yukikamome316 commented
積み上げ棒グラフを使って、棒グラフの色をデータごとに塗り分けられないかな？

2024-12-01 09:09 UTC, yukikamome316 commented
```
pnpm lintfix
```
が使えるよ

2024-12-01 09:20 UTC, nomanoma121 commented
> ```
> pnpm lintfix
> ```
> 
> が使えるよ

2024-12-01 11:53 UTC, nomanoma121 commented
![スクリーンショット 2024-12-01 205304](https://github.com/user-attachments/assets/6c55fe6e-65e7-4a8f-86f2-fb950d76c988)
縦積みグラフはこんな感じでいいですかね？

2024-12-01 12:58 UTC, yukikamome316 commented
> 縦積みグラフはこんな感じでいいですかね？5色をサイクルさせる感じです
> 
> ↑いま体調で色を変えるように修正中です

こんな感じで縦に一色だけ表示させたい！

![image](https://github.com/user-attachments/assets/3291e240-f39c-48be-9e5b-fd396acf9b08)

2024-12-01 14:22 UTC, yukikamome316 requested changes
alcoho-rhythm直下の3つのファイルとディレクトリを消してほしい！
![image](https://github.com/user-attachments/assets/957f54a4-f424-4d66-9f29-b5a2703c4937)

2024-12-02 01:11 UTC, nomanoma121 commented
![スクリーンショット 2024-12-02 101100](https://github.com/user-attachments/assets/150d870e-ec50-48e0-bf3d-a6f7527c173f)
グラフこんな感じになりました

2024-12-02 09:26 UTC, shigekk approved these changes

2024-12-02 09:26 UTC, yukikamome316 approved these changes

2024-12-02 09:26 UTC, merged