registerのがわだけ作った
yukikamome316/alcoho-rhythm pull request #5
Opened 2024-10-17 06:02 UTC by shigekk

関数はこれから作ります
cssも仮です

2024-10-17 16:03 UTC, yukikamome316 requested changes

2024-10-17 16:03 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +      </div>
デザインはこれでいいと思う
あとはトグルボタンにして、この下に登録ボタンを作ろう

2024-10-17 16:03 UTC, yukikamome316 commented on client/src/register/register.css
画面サイズを小さくしたとき、背景の右半分がおかしくなる？

![image](https://github.com/user-attachments/assets/e21a67f5-2996-4c4d-b575-7fbab9febf85)

2024-10-17 16:03 UTC, yukikamome316 commented on client/src/register/register.css
> +}
`Body` タグがあるコンポーネントの css に実装した方が、保守の関係上良い
`client/src/index.css` の L25

2024-10-17 16:03 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +        <input type="date" />
日付範囲のバリデーションを入れよう (`0002/02/31` が入力できてしまう)
https://stackoverflow.com/questions/72068835/how-to-validate-inputtype-date-in-react

2024-10-17 16:03 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +              <th>酒名</th>
「お酒の種類」の方がラフでいいかも

2024-10-17 16:03 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +            </tr>
目安のアルコール度数と、似たお酒を固めて入力しやすいようにジャンルを増やすといいと思う
あと「数量を入力」と書くと、入力必須感出るから `placeholder` はなくてもいい気がするな
その代わり、テキストボックスの後ろ側に「杯」って文字を入れて、「○○杯」と表示されるのがいいかも

2024-10-17 16:03 UTC, yukikamome316 commented on client/src/App.jsx
>  import Signup from './Signup';
```suggestion
import { BrowserRouter, Route, Routes, Link } from 'react-router-dom';
import Dashboard from './Dashboard';
import Register from './register/Register';
import Signup from './Signup';
```

2024-10-17 16:03 UTC, yukikamome316 commented on client/src/register/register.css
> +}
最終行に改行入れてほしい

2024-10-18 04:43 UTC, shigekk commented on client/src/register/Register.jsx
> +      </div>
トグルボタンにすると複数選択できちゃうんですけど、なにかいい方法ありますか？

2024-10-18 07:01 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +      </div>
`useState` を使って実装しようか
https://stackoverflow.com/questions/71108354/dynamic-react-toggle-button-for-multiple-elements

2024-10-18 16:55 UTC, yukikamome316 commented
@shigekk 
過去のコミットメッセージを命名規則に従って修正してほしい！
あと、このPRのタイトルも同じ感じで接頭辞つけるといいよ

2024-10-27 06:13 UTC, yukikamome316 requested changes

2024-10-27 06:13 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +      alert("2000年1月1日から今日までの日付を選択してください。");
`alert` の代わりに日付のダイアログの下に「2000年1月1日から今日までの日付を選択できます」と青文字で表示する方がいいかも

2024-10-27 06:13 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +      alert("体調を選択してください。");
そもそも登録ボタンを押せないようにしておけばいいと思う

2024-10-27 06:13 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +    alert("登録されました");
これは `alert` なしで `/dashboard` にリダイレクトされるようにした方が分かりやすい気がする

2024-10-27 06:13 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +                <input type="number" min="0" /> 缶
わざわざ飲んでないお酒に対して「0」と入力しないといけないことを連想させないように、`placeholder` で未入力の場合は「0缶」と表示させておこう

2024-10-27 06:15 UTC, yukikamome316 requested changes
追加でもう一件お願い！

2024-10-27 06:15 UTC, yukikamome316 commented on client/src/register/Register.jsx
> +        <label>飲酒した日付を選択してください</label>
文字の選択範囲の高さを低くしよう
![image](https://github.com/user-attachments/assets/3964dbcb-3de1-49d8-80ac-da9fa8d060c9)

2024-10-29 14:44 UTC, shigekk commented on client/src/register/Register.jsx
> +      alert("体調を選択してください。");
ボタンを押さずに
![image](https://github.com/user-attachments/assets/eda85cbd-e9ec-493d-bd4c-a3d38496f01f)
を表示させる方法が分からないです

2024-10-30 14:00 UTC, yukikamome316 requested changes
どっちが良くてどっちが悪いのか書いた方がよさそう
![image](https://github.com/user-attachments/assets/f451252d-8452-451a-aae5-a56899ca2daa)

2024-10-30 15:36 UTC, yukikamome316 approved these changes
よさそう！お疲れ様！

2024-10-30 15:36 UTC, merged