ER図の作成
yukikamome316/alcoho-rhythm pull request #8
Opened 2024-10-17 15:01 UTC by hana-rs

2024-10-17 15:11 UTC, yukikamome316 requested changes

2024-10-17 15:11 UTC, yukikamome316 commented on README.md
> +# ER図
h2 (`##`)から始めてほしい！

2024-10-17 15:11 UTC, yukikamome316 commented on README.md
> +    }
https://qiita.com/tsweblabo/items/0a0c14d236d896b7f4a7
型名はこれに合わせてほしい

2024-10-17 15:11 UTC, yukikamome316 commented on README.md
> +        text login_pw "ログインPW"
属性名を `password` にすると分かりやすいと思う

2024-10-17 15:11 UTC, yukikamome316 commented on README.md
> +        int user_id PK "ユーザーID"
`user_id` じゃなくて `id` でいいよ

2024-10-17 15:11 UTC, yukikamome316 commented on README.md
> +    data {
`data` だと何のデータかわからないから、後のために明示してほしい

2024-10-17 15:11 UTC, yukikamome316 commented on README.md
> +        int drinking_id PK "飲酒ID"
これも `id` で OK

2024-10-17 15:11 UTC, yukikamome316 commented on README.md
> +    users ||--|{ data : ""
`data` が0件でもOKなので一応修正してほしい

2024-10-17 15:55 UTC, shigekk approved these changes, later dismissed

2024-10-19 03:46 UTC, shigekk approved these changes

2024-10-19 04:11 UTC, yukikamome316 approved these changes

2024-10-19 04:11 UTC, merged