テーブル作成のクエリを実装
yukikamome316/alcoho-rhythm pull request #9
Opened 2024-10-19 11:25 UTC by nomanoma121

テーブルを作成するクエリを実装しました。とりあえずデータベースのファイルをdatabase.dbとしています。

2024-10-19 15:09 UTC, yukikamome316 requested changes

2024-10-19 15:09 UTC, yukikamome316 commented on server/queries.js
クエリ自体はぱっと見よさそう
あとは queries.js ではDB操作を行わないで、クエリを持つオブジェクトを定義だけして後から server.js で呼び出せるような形にしておいてもらえると助かる！
以下のブログに載ってる queries.js を参考にするといいかも (`db.prepare` しないで文字列だけ定義するイメージ)
https://blog.maximum.vc/blog/2023/webken/8/#%E7%89%B9%E5%AE%9A%E3%81%AE%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%81%8C%E6%8A%95%E7%A8%BF%E3%81%97%E3%81%9F%E3%83%84%E3%82%A4%E3%83%BC%E3%83%88%E4%B8%80%E8%A6%A7%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B

2024-10-20 05:08 UTC, nomanoma121 commented
![スクリーンショット 2024-10-20 140814](https://github.com/user-attachments/assets/86d4142f-30cf-4b92-adcf-e7859f1b2a9c)

2024-10-20 05:12 UTC, nomanoma121 commented
![スクリーンショット 2024-10-20 141224](https://github.com/user-attachments/assets/a910e374-edfa-4424-92f1-dcbd5f5399fe)

2024-10-21 03:39 UTC, yukikamome316 requested changes

2024-10-21 03:39 UTC, yukikamome316 commented on server/database.db
これはコミットに含めないで削除してほしい！

2024-10-21 03:39 UTC, yukikamome316 commented on server/database.js
これは何？

2024-10-21 03:39 UTC, yukikamome316 commented on server/queries.js
> +export default queries;
最終行に改行を入れてほしい！

2024-10-21 03:39 UTC, yukikamome316 commented on server/server.js
> +db.prepare(queries.DrinkingRecords.createTable).run();
```suggestion
const db = new Database("database.db");

func migrate(db) {
  db.prepare(queries.Users.createTable).run();
  db.prepare(queries.DrinkingRecords.createTable).run();
}
```

こうするのがいいと思っていて、最後の `serve` の前に `migrate` するイメージ

2024-10-21 08:38 UTC, nomanoma121 commented on server/database.db
gitignoreに追加する感じですか？

2024-10-21 08:38 UTC, nomanoma121 commented on server/database.js
おそらくミスで追加していました

2024-10-21 09:53 UTC, yukikamome316 requested changes

2024-10-21 09:53 UTC, yukikamome316 commented on server/database.db
できれば `../.gitignore` に追加してほしい

2024-10-21 09:53 UTC, yukikamome316 commented on server/.gitignore
> +*db
```suggestion
*db

```

2024-10-21 09:53 UTC, yukikamome316 commented on server/server.js
> +migrate(db);
一番下にある `serve` の直前で `migrate` を呼び出してほしい！

2024-10-21 10:05 UTC, yukikamome316 approved these changes

2024-10-21 10:05 UTC, merged